// trello-vue/src/components/Navbar.vue
<template>
  <nav class="header">
    <div class="header-logo">
      <router-link to="/">Trello</router-link>
    </div>
    <div class="header-auth">
      <a
        href=""
        v-if="isAuth"
        @click.prevent="logout"
      >
        Logout
      </a>
      <router-link
        v-else
        to="/login"
      >
        Login
      </router-link>
    </div>
  </nav>
</template>

<script>
import { mapGetters, mapMutations } from 'vuex';

export default {
  computed: {
    ...mapGetters([
      'isAuth',
    ])
  },

  methods: {
    ...mapMutations([
      'LOGOUT',
    ]),
    logout() {
      this.LOGOUT();
      this.$router.push('/login');
    }
  }
}
</script>

<style>
.header {
  flex: none;
  background-color: rgba(0,0,0,.15);
  height: 32px;
  padding: 4px;
}
.header a {
  display: block;
  height: 30px;
  line-height: 30px;
  text-decoration: none;
  color: rgba(255,255,255,.5);
}
.header-logo {
  position: absolute;
  left: 50%;
  top: 7px;
  margin-left: -30px;
  text-align: center;
  font-weight: bolder;
  font-size: 24px;
}
.header-logo a:hover,
.header-logo a:focus {
  color: rgba(255,255,255,.9);
}
.header-auth {
  position: absolute;
  right: 15px;
  top: 5px;
}
.header-auth a {
  border-radius: 2px;
  padding: 0 10px;
  background-color: rgba(255,255,255, .5);
  color: white;
  transition: all .3s;
}
.header-auth a:hover,
.header-auth a:focus {
  background-color: rgba(255,255,255, .3);
}
</style>

// trello-react/src/modules/Header/containers/NavBar.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import styled from 'styled-components';

const Nav = styled.nav`
  display: flex;
  align-items: center;
  justify-content: space-between;
  background-color: rgba(0,121,191,0);
  padding: 1rem;

  &.auth-buttons {
    display: flex;
    align-items: center;
  }
`;
const H1 = styled.h1`
  color: #fff;
`;
const Button = styled(Link)`
  margin-left: 1rem;
  font-weight: bold;
  padding: 7px;
  border: 2px solid #fff;
  border-radius: ${(props) => props.theme.mainBorderRadius};
  background-color: ${(props) => (props.isSignup ? '#fff' : '')};
  color: ${(props) => (props.isSignup ? props.theme.mainThemeColor : '#fff')};
  line-height: 1;

  &:hover {
    color: ${(props) => (props.isSignup ? props.theme.mainThemeColor : '#fff')};
  }
`;

export default function NavBar() {
  return (
    <Nav>
      <H1>Trello</H1>
      <div className="auth-buttons">
        <Button to="/signin">Sign In</Button>
        <Button isSignup to="/signup">Sign Up</Button>
      </div>
    </Nav>
  );
}
